const KEY='swdm_rp_db_v3';
const seed={settings:{unit:'KMP KATOWICE',dept:'WRD',call:'MO-102',operator:'ONLINE',theme:'dark',sound:true,alerts:true,autoLock:2,compact:false},officers:[],people:[{id:'P-1001',name:'Jan Kowalski',pesel:'99041212345',dob:'12.04.1999',address:'ul. Demo 15, Katowice',status:'CZYSTY',history:[{date:'19.09.2026 12:40',type:'KONTROLA DROGOWA',text:'Kontrola szkoleniowa RP. Dokumenty zweryfikowane.',author:'ADMIN RP'}],photo:''}],vehicles:[{id:'V-1001',reg:'KR RP01',vin:'RPVIN000001',make:'Skoda',model:'Octavia',year:'2021',owner:'P-1001',oc:'AKTYWNE',inspection:'AKTYWNE',stolen:false}],tickets:[],wanted:[],interventions:[{id:'I-1001',priority:'1',title:'Kolizja drogowa',address:'ul. Demo 12, Katowice',desc:'Zdarzenie szkoleniowe RP',status:'NOWE'}],notes:[],messages:[{time:'13:42',from:'DYSPOZYTOR RP',text:'MO-102 — potwierdź status patrolu.'}],documents:[]};
let D=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
async function syncAccounts(){
  const list=Array.isArray(window.RP_ACCOUNTS)?window.RP_ACCOUNTS:[];
  for(const a of list){
    if(!a.id||!a.password||!a.pin) continue;
    const passHash=await sha256(a.password), pinHash=await sha256(a.pin);
    const existing=D.officers.find(o=>o.id===a.id);
    const data={id:a.id,name:a.name||a.id,rank:a.rank||'funkcjonariusz',unit:D.settings.unit,dept:a.dept||D.settings.dept,call:a.call||'MO-999',role:a.role||'funkcjonariusz',passHash,pinHash,active:a.active!==false};
    if(existing) Object.assign(existing,data); else D.officers.push(data);
  }
  save();
}
localStorage.setItem(KEY,JSON.stringify(D));
const accountsReady=syncAccounts();
let current='dashboard', last=Date.now(), locked=false, currentOfficer=null, failed=0, blockedUntil=0;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const tabs=[['dashboard','MENU'],['people','OSOBY'],['vehicles','POJAZDY'],['licences','UPRAWNIENIA'],['tickets','MANDATY'],['wanted','POSZUKIWANI'],['interventions','INTERWENCJE'],['notes','NOTATKI'],['comms','ŁĄCZNOŚĆ'],['documents','DOKUMENTACJA'],['settings','USTAWIENIA'],['admin','ADMINISTRACJA']];
$('#tabs').innerHTML=tabs.map(x=>`<button class="${x[0]=='admin'?'admin':''}" data-page="${x[0]}">${x[1]}</button>`).join(''); document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{current=b.dataset.page;beep();render()});
function save(){localStorage.setItem(KEY,JSON.stringify(D))} function now(){return new Date().toLocaleString('pl-PL')} function field(l,id,v='',t='text'){return `<div class=field><label>${l}</label><input id="${id}" type="${t}" value="${esc(v)}"></div>`} function page(t,b){$('#main').innerHTML=`<div class=page><h1>${t}</h1>${b}</div>`;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===current))}
function render(){if(current==='dashboard')dashboard();if(current==='people')people();if(current==='vehicles')vehicles();if(current==='licences')licences();if(current==='tickets')tickets();if(current==='wanted')wanted();if(current==='interventions')interventions();if(current==='notes')notes();if(current==='comms')comms();if(current==='documents')documents();if(current==='settings')settings();if(current==='admin')admin();document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{current=b.dataset.go;beep();render()})}
function dashboard(){page('Terminal mobilny',`<div class=notice>ŚRODOWISKO RP / V3.5 — dane fikcyjne, przechowywane lokalnie na tym urządzeniu.</div><div class=card><b>${esc(currentOfficer?.name||'—')}</b><small>${esc(currentOfficer?.id||'')} · ${esc(currentOfficer?.role||'')}</small></div><div class=grid>${tabs.slice(1).map(x=>`<button class=tile data-go="${x[0]}"><b>${x[1]}</b><small>Otwórz moduł</small></button>`).join('')}</div>`)}
function people(){page('OSOBY',`<div class=field><label>SZUKAJ</label><input id=pq placeholder="imię, nazwisko, ID lub fikcyjny PESEL"></div><button class=primary id=np>+ DODAJ OSOBĘ</button><div id=pl></div>`);let draw=()=>{$('#pl').innerHTML=D.people.filter(p=>JSON.stringify(p).toLowerCase().includes($('#pq').value.toLowerCase())).map(p=>`<div class=item><b>${esc(p.name)}</b><small>${esc(p.id)} · PESEL RP: ${esc(p.pesel)} · ${esc(p.status)}</small><div class=actions><button data-p="${p.id}">AKTA</button></div></div>`).join('')||'<div class=muted>Brak wyników.</div>';document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>person(b.dataset.p))};$('#pq').oninput=draw;$('#np').onclick=()=>personForm();draw()}
function person(id){let p=D.people.find(x=>x.id===id);page('AKTA OSOBY',`<div class=card>${p.photo?`<img class=photo src="${p.photo}">`:''}<h2>${esc(p.name)}</h2><p>ID: ${esc(p.id)} · PESEL RP: ${esc(p.pesel)}</p><p>Data: ${esc(p.dob)} · Adres: ${esc(p.address)}</p><p>Status: <b>${esc(p.status)}</b></p><div class=actions><button id=hist>+ WPIS</button><button id=edit>EDYTUJ</button></div></div><h2>HISTORIA</h2><div class=timeline>${(p.history||[]).map(e=>`<div class=event><b>${esc(e.date)} · ${esc(e.type)}</b><div>${esc(e.text)}</div><small>${esc(e.author)}</small></div>`).join('')||'<div class=muted>Brak wpisów.</div>'}</div>`);$('#hist').onclick=()=>historyForm(p);$('#edit').onclick=()=>personForm(p)}
function personForm(p){page(p?'EDYTUJ OSOBĘ':'DODAJ OSOBĘ',`<div class=card>${field('Imię i nazwisko','n',p?.name)}${field('Fikcyjny PESEL','pes',p?.pesel)}${field('Data urodzenia','dob',p?.dob)}${field('Adres','addr',p?.address)}<div class=field><label>Status</label><select id=st><option>CZYSTY</option><option>POSZUKIWANY</option><option>DO WERYFIKACJI</option></select></div><div class=field><label>Zdjęcie RP (opcjonalnie)</label><input id=ph type=file accept="image/*"></div><button class=primary id=sp>ZAPISZ</button></div>`);if(p)$('#st').value=p.status;$('#sp').onclick=()=>{let o=p||{id:'P-'+Date.now(),history:[],photo:''};let f=$('#ph').files[0];const finish=photo=>{Object.assign(o,{name:$('#n').value,pesel:$('#pes').value,dob:$('#dob').value,address:$('#addr').value,status:$('#st').value,photo:photo??o.photo});if(!p)D.people.unshift(o);save();current='people';beep();render()};if(f){let r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(f)}else finish(o.photo)}}
function historyForm(p){page('DODAJ WPIS DO AKT',`<div class=card>${field('Rodzaj','ht','KONTROLA DROGOWA')}<div class=field><label>Opis</label><textarea id=hx rows=5></textarea></div><button class=primary id=sh>DODAJ</button></div>`);$('#sh').onclick=()=>{p.history.unshift({date:now(),type:$('#ht').value,text:$('#hx').value,author:currentOfficer?.name||'RP'});save();beep();person(p.id)}}
function vehicles(){page('POJAZDY',`<button class=primary id=nv>+ DODAJ POJAZD</button><div class=field><label>SZUKAJ</label><input id=vq placeholder="rejestracja, VIN, marka"></div><div id=vl></div>`);let d=()=>$('#vl').innerHTML=D.vehicles.filter(v=>JSON.stringify(v).toLowerCase().includes($('#vq').value.toLowerCase())).map(v=>`<div class=item><b>${esc(v.reg)} · ${esc(v.make)} ${esc(v.model)}</b><small>VIN RP: ${esc(v.vin)} · OC: ${v.oc} · Badanie: ${v.inspection} · Skradziony: ${v.stolen?'TAK':'NIE'}</small></div>`).join('')||'<div class=muted>Brak wyników.</div>';$('#vq').oninput=d;$('#nv').onclick=()=>vehicle();d()}
function licences(){page('UPRAWNIENIA',`<div class=card>${field('Numer prawa jazdy RP','ln','RP-LIC-1001')}<button class=primary id=checkLic>SPRAWDŹ</button></div><div id=lr></div>`);$('#checkLic').onclick=()=>{$('#lr').innerHTML='<div class=card><b class=ok>STATUS: AKTYWNE</b><p>Kategorie: B</p><p>Punkty: 6</p><p>Zakazy: brak</p></div>';beep()}}
function tickets(){page('MANDATY',`<div class=card>${field('Osoba ID RP','tn')}${field('Wykroczenie','to')}${field('Kwota zł','ta','0','number')}${field('Punkty','tp','0','number')}<button class=primary id=stt>WYSTAW MANDAT</button></div><h2>Historia mandatów</h2><div>${D.tickets.map(t=>`<div class=item><b>${esc(t.person)}</b><small>${esc(t.offence)} · ${t.amount} zł · ${t.points} pkt · ${esc(t.date)}</small></div>`).join('')||'<div class=muted>Brak mandatów.</div>'}</div>`);$('#stt').onclick=()=>{let person=D.people.find(p=>p.id===$('#tn').value);let t={id:'T-'+Date.now(),person:$('#tn').value,offence:$('#to').value,amount:$('#ta').value,points:$('#tp').value,date:now(),author:currentOfficer?.id||'RP'};D.tickets.unshift(t);if(person)person.history.unshift({date:now(),type:'MANDAT',text:`${t.offence}; ${t.amount} zł; ${t.points} pkt.`,author:currentOfficer?.name||'RP'});save();alert('Mandat RP zapisany lokalnie.');beep();render()}}
function wanted(){page('POSZUKIWANI',`<div class=notice>Fikcyjna lista RP.</div><button class=primary id=nw>+ DODAJ</button>${D.wanted.map(w=>`<div class=item><b>${esc(w.name)}</b><small>${esc(w.case)} · zagrożenie: ${esc(w.risk)}</small><p>${esc(w.desc)}</p></div>`).join('')||'<div class=muted>Brak wpisów.</div>'}`);$('#nw').onclick=()=>wantedForm()}
function interventions(){page('INTERWENCJE',`<button class=primary id=ni>+ NOWE ZGŁOSZENIE</button><div id=il>${D.interventions.map(i=>`<div class=item><b>PRIORYTET ${esc(i.priority)} · ${esc(i.title)}</b><small>${esc(i.address)} · ${esc(i.status)}</small><p>${esc(i.desc)}</p><div class=actions><button data-nav="${i.id}">NAWIGUJ</button><button data-disp="${i.id}">POTWIERDŹ</button></div></div>`).join('')}</div>`);$('#ni').onclick=interventionForm;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{alert('Nawigacja DEMO — brak połączenia z mapami.');beep()});document.querySelectorAll('[data-disp]').forEach(b=>b.onclick=()=>{let i=D.interventions.find(x=>x.id===b.dataset.disp);if(i)i.status='PRZYJĘTE';save();render();beep()})}
function interventionForm(){page('NOWA INTERWENCJA',`<div class=card>${field('Priorytet','ip','2')}${field('Tytuł','it','Zgłoszenie')}${field('Adres','ia')}${field('Opis','ix')}<button class=primary id=si>ZAPISZ</button></div>`);$('#si').onclick=()=>{D.interventions.unshift({id:'I-'+Date.now(),priority:$('#ip').value,title:$('#it').value,address:$('#ia').value,desc:$('#ix').value,status:'NOWE'});save();newAlertSound();current='interventions';render()}}
function notes(){page('NOTATKI',`<div class=card>${field('Tytuł','nt')}${field('Treść','nx')}<button class=primary id=sn>ZAPISZ</button></div>${D.notes.map(n=>`<div class=item><b>${esc(n.title)}</b><p>${esc(n.text)}</p><small>${esc(n.date)}</small></div>`).join('')}`);$('#sn').onclick=()=>{D.notes.unshift({title:$('#nt').value,text:$('#nx').value,date:now(),author:currentOfficer?.id});save();beep();render()}}
function comms(){page('ŁĄCZNOŚĆ',`<div class=card><div class=field><label>WIADOMOŚĆ DO DYSPOZYTORA</label><textarea id=cm rows=3></textarea></div><button class=primary id=send>WYŚLIJ</button></div>${D.messages.map(m=>`<div class=item><b>${esc(m.from)} · ${esc(m.time)}</b><p>${esc(m.text)}</p></div>`).join('')}`);$('#send').onclick=()=>{D.messages.unshift({time:new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'}),from:currentOfficer?.call||'PATROL RP',text:$('#cm').value});save();beep();render()}}
function documents(){page('DOKUMENTACJA',`<div class=card>${field('Typ dokumentu','dt','NOTATKA SŁUŻBOWA')}${field('Tytuł','du')}${field('Treść','dx')}<button class=primary id=sd>ZAPISZ DOKUMENT</button></div><div>${D.documents.map(d=>`<div class=item><b>${esc(d.type)} · ${esc(d.title)}</b><small>${esc(d.date)} · ${esc(d.author)}</small><p>${esc(d.text)}</p></div>`).join('')||'<div class=muted>Brak dokumentów.</div>'}</div>`);$('#sd').onclick=()=>{D.documents.unshift({id:'DOC-'+Date.now(),type:$('#dt').value,title:$('#du').value,text:$('#dx').value,date:now(),author:currentOfficer?.name||'RP'});save();beep();render()}}
function settings(){page('USTAWIENIA',`<div class=card><h2>PROFIL TERMINALA</h2>${field('Jednostka','su',D.settings.unit)}${field('Wydział','sdpt',D.settings.dept)}${field('Kryptonim','sc',D.settings.call)}<div class=field><label>Status operatora</label><select id=sox><option>ONLINE</option><option>PAUZA</option><option>OFFLINE</option></select></div></div><div class=card><h2>INTERFEJS</h2><div class=field><label>Dźwięki interfejsu</label><select id=sound><option value="true">WŁĄCZONE</option><option value="false">WYŁĄCZONE</option></select></div><div class=field><label>Dźwięk alarmu interwencji</label><select id=alerts><option value="true">WŁĄCZONY</option><option value="false">WYŁĄCZONY</option></select></div><div class=field><label>Automatyczna blokada</label><select id=locktime><option value="1">1 minuta</option><option value="2">2 minuty</option><option value="5">5 minut</option><option value="10">10 minut</option><option value="0">Wyłączona</option></select></div><div class=field><label>Tryb kompaktowy</label><select id=compact><option value="false">STANDARD</option><option value="true">KOMPAKTOWY</option></select></div></div><div class=card><h2>SESJA</h2><p>Zalogowany: <b>${esc(currentOfficer?.name||'—')}</b><br>ID: ${esc(currentOfficer?.id||'—')} · Rola: ${esc(currentOfficer?.role||'—')}</p><div class=actions><button class=primary id=logoutSettings>WYLOGUJ</button></div></div><div class=card><h2>LOKALNA BAZA RP</h2><p>Dane są zapisane wyłącznie w pamięci tej przeglądarki na tym urządzeniu.</p><div class=actions><button id=export>EKSPORT BACKUP</button><label class=buttonlike for=importFile>IMPORT BACKUP</label><input id=importFile type=file accept="application/json" hidden><button id=clearData>WYCZYŚĆ DANE RP</button></div></div><button class=primary id=ss>ZAPISZ USTAWIENIA</button>`);$('#sox').value=D.settings.operator;$('#sound').value=String(D.settings.sound!==false);$('#alerts').value=String(D.settings.alerts!==false);$('#locktime').value=String(D.settings.autoLock??2);$('#compact').value=String(D.settings.compact===true);$('#ss').onclick=()=>{D.settings={...D.settings,unit:$('#su').value,dept:$('#sdpt').value,call:$('#sc').value,operator:$('#sox').value,sound:$('#sound').value==='true',alerts:$('#alerts').value==='true',autoLock:Number($('#locktime').value),compact:$('#compact').value==='true'};document.body.classList.toggle('compact',D.settings.compact);save();updateHeader();beep();render()};$('#logoutSettings').onclick=()=>{currentOfficer=null;location.reload()};$('#export').onclick=exportData;$('#importFile').onchange=e=>importData(e.target.files[0]);$('#clearData').onclick=()=>{if(confirm('Wyczyścić całą lokalną bazę RP?')){localStorage.removeItem(KEY);location.reload()}}}
function admin(){if(currentOfficer?.role!=='administrator'){page('ADMINISTRACJA RP','<div class=notice>Brak uprawnień administratora.</div>');return}page('ADMINISTRACJA RP',`<div class=notice>Panel administratora modyfikuje wyłącznie lokalną bazę fikcyjną.</div><div class=grid><button class=tile id=no><b>FUNKCJONARIUSZ</b><small>Dodaj konto RP</small></button><button class=tile id=np><b>OSOBA</b><small>Dodaj kartę</small></button><button class=tile id=nv><b>POJAZD</b><small>Dodaj pojazd</small></button><button class=tile id=nw><b>POSZUKIWANY</b><small>Dodaj wpis</small></button><button class=tile id=reset><b>RESET DEMO</b><small>Wyczyść lokalną bazę</small></div><h2>Funkcjonariusze</h2>${D.officers.map(o=>`<div class=item><b>${esc(o.name)}</b><small>${esc(o.id)} · ${esc(o.rank)} · ${esc(o.role)} · ${o.active?'AKTYWNY':'ZABLOKOWANY'}</small><button data-toggle="${o.id}">${o.active?'ZABLOKUJ':'ODBLOKUJ'}</button></div>`).join('')}`);$('#no').onclick=()=>officer();$('#np').onclick=()=>personForm();$('#nv').onclick=()=>vehicle();$('#nw').onclick=()=>wantedForm();$('#reset').onclick=()=>{if(confirm('Usunąć lokalną bazę RP i przywrócić dane demo?')){localStorage.removeItem(KEY);location.reload()}};document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{let o=D.officers.find(x=>x.id===b.dataset.toggle);if(o&&o.id!=='ADMIN-001')o.active=!o.active;save();render()})}
function officer(){page('DODAJ FUNKCJONARIUSZA RP',`<div class=card>${field('ID','oi','F-'+Date.now())}${field('Imię i nazwisko','on')}${field('Stopień','or','st. post.')}${field('Wydział','od','WRD')}${field('Kryptonim','oc','MO-999')}${field('Hasło','op','','password')}${field('PIN','opin','','password')}<div class=field><label>Rola</label><select id=role><option value="funkcjonariusz">Funkcjonariusz</option><option value="dowodca">Dowódca</option><option value="administrator">Administrator</option></select></div><button class=primary id=so>ZAPISZ</button></div>`);$('#so').onclick=async()=>{if(!$('#oi').value||!$('#op').value||!$('#opin').value){alert('Uzupełnij ID, hasło i PIN.');return}let [passHash,pinHash]=await Promise.all([sha256($('#op').value),sha256($('#opin').value)]);D.officers.push({id:$('#oi').value,name:$('#on').value,rank:$('#or').value,unit:D.settings.unit,dept:$('#od').value,call:$('#oc').value,role:$('#role').value,passHash,pinHash,active:true});save();beep();admin()}}
function vehicle(){page('DODAJ POJAZD RP',`<div class=card>${field('Rejestracja','vr')}${field('VIN RP','vv')}${field('Marka','vm')}${field('Model','vmo')}${field('Rok','vy')}${field('Właściciel ID RP','vo')}<button class=primary id=sv>ZAPISZ</button></div>`);$('#sv').onclick=()=>{D.vehicles.push({id:'V-'+Date.now(),reg:$('#vr').value,vin:$('#vv').value,make:$('#vm').value,model:$('#vmo').value,year:$('#vy').value,owner:$('#vo').value,oc:'AKTYWNE',inspection:'AKTYWNE',stolen:false});save();current='vehicles';render()}}
function wantedForm(){page('DODAJ POSZUKIWANEGO RP',`<div class=card>${field('Osoba','wn')}${field('Sygnatura RP','wc')}${field('Zagrożenie','wr','NISKI')}${field('Opis','wd')}<button class=primary id=sw>ZAPISZ</button></div>`);$('#sw').onclick=()=>{D.wanted.push({name:$('#wn').value,case:$('#wc').value,risk:$('#wr').value,desc:$('#wd').value});save();current='wanted';render()}}
async function sha256(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function authorize(id,pass,pin){if(Date.now()<blockedUntil){alert('Dostęp chwilowo zablokowany.');return null}let o=D.officers.find(x=>x.id===id&&x.active);if(!o){fail();return null}let [ph,pinh]=await Promise.all([sha256(pass),sha256(pin)]);if(ph!==o.passHash||pinh!==o.pinHash){fail();return null}failed=0;return o}
function fail(){failed++;if(failed>=5){blockedUntil=Date.now()+30000;failed=0}alert('Nieprawidłowe dane logowania.')}
function beep(){if(D.settings.sound===false)return;try{let c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=760;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.045)}catch{}}
function newAlertSound(){if(D.settings.alerts===false)return;try{let c=new AudioContext();[0,1,2].forEach((n)=>{let o=c.createOscillator(),g=c.createGain();o.frequency.value=650+n*180;g.gain.value=.06;o.connect(g);g.connect(c.destination);o.start(c.currentTime+n*.09);o.stop(c.currentTime+n*.09+.07)})}catch{} }
function updateHeader(){let h=$('#unitHeader');if(h)h.textContent=`${D.settings.unit} | ${D.settings.dept} | ${D.settings.call} | ${D.settings.operator} | ${new Date().toLocaleTimeString('pl-PL')} | LTE | GPS | 88%`}
function exportData(){let blob=new Blob([JSON.stringify(D,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SWD-M-RP-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.officers||!x.people)throw Error();D=x;save();alert('Backup zaimportowany.');location.reload()}catch{alert('Nieprawidłowy backup.')}};r.readAsText(file)}
function touch(){last=Date.now()}['click','touchstart','keydown','input'].forEach(e=>document.addEventListener(e,touch,{passive:true}));setInterval(()=>{updateHeader();if(D.settings.autoLock>0&&Date.now()-last>D.settings.autoLock*60000&&!locked&&!$('#login').classList.contains('hidden'))return;if(D.settings.autoLock>0&&Date.now()-last>D.settings.autoLock*60000&&!locked){locked=true;$('#app').classList.add('hidden');$('#locked').classList.remove('hidden')}},1000);
$('#loginBtn').onclick=async()=>{await accountsReady;let o=await authorize($('#loginId').value.trim(),$('#loginPass').value,$('#loginPin').value);if(o){currentOfficer=o;$('#loginform').classList.add('hidden');$('#boot').classList.remove('hidden');setTimeout(()=>{$('#login').classList.add('hidden');$('#app').classList.remove('hidden');updateHeader();render()},1100)}};
$('#unlockBtn').onclick=async()=>{if(currentOfficer&&await sha256($('#unlockPin').value)===currentOfficer.pinHash){locked=false;last=Date.now();$('#unlockPin').value='';$('#locked').classList.add('hidden');$('#app').classList.remove('hidden');render()}else alert('Nieprawidłowy PIN.')};
$('#logoutBtn').onclick=()=>{currentOfficer=null;location.reload()};
document.body.classList.toggle('compact',D.settings.compact===true);updateHeader();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
